language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.5.5
  - DJANGO=1.5.6
  - DJANGO=1.5.7
  - DJANGO=1.5.8
  - DJANGO=1.6.2
  - DJANGO=1.6.3
  - DJANGO=1.6.4
  - DJANGO=1.6.5

install:
  - pip install -q Django==$DJANGO
  - pip install -q requests
  - pip install -q flake8
  - pip install -q python-coveralls coverage
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install importlib; fi"
  - python setup.py install


before_script:
  - flake8 --exclude=migrations --ignore=W391,E501,E225 django_ulogin

after_success:
  coveralls --config_file=coverage.rc

script:
  - coverage run --include=django_ulogin/* ./tests.py
