language: python

python:
  - "2.6"
  - "2.7"

env:
  - DJANGO=1.5.5
  - DJANGO=1.6.2

install:
  - pip install -q Django==$DJANGO
  - pip install -q requests
  - pip install -q flake8
  - pip install -q importlib
  - python setup.py install

before_script:
  - flake8 --exclude=migrations --ignore=W391,E501,E225 django_ulogin

script:
  - python tests.py


